version: '3.8'

services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: apibuilder
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql  # Persistent storage for MySQL
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      timeout: 5s

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    depends_on:
      mysql:
        condition: service_healthy  # Ensures MySQL is ready before backend starts
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: apibuilder
    ports:
      - "3001:3001"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app              # Mount the local code into the container
      - /app/node_modules            # Exclude node_modules to prevent conflicts
    environment:
      - CHOKIDAR_USEPOLLING=true     # Fix file watching issues inside Docker

volumes:
  mysql_data:  # Named volume for MySQL persistence